management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: 'true'
  endpoint:
    health:
      show-details: always
spring:
  application:
    name: circuit-breaker-pattern
  jackson:
    serialization:
      indent_output: 'true'

logging:
  level:
    io.github.resilience4j.retry: DEBUG

rest-service:
  pin-code:
     base-url: 'https://api.postalpincode.in'
     timeout: 3000


resilience4j:
  ratelimiter:
    instances:
      searchPinCode:
        limitForPeriod: 2
        limitRefreshPeriod: 10s
        timeoutDuration: 0
      searchPostOffice:
        limitForPeriod: 2
        limitRefreshPeriod: 10s
        timeoutDuration: 5
  bulkhead:
    instances:
      searchPinCode:
        maxConcurrentCalls: 2 # Max concurrent calls allowed
        maxWaitDuration: 0 # Max time a request waits in the queue before failing
      searchPostOffice:
        maxConcurrentCalls: 1
        maxWaitDuration: 2
  retry:
    instances:
      searchPinCode:
        maxAttempts: '3'
        waitDuration: 1s
        retryExceptions:
          - java.lang.Exception
        ignoreExceptions:
          - com.vks.cbp.exception.InvalidPinCodeException
      searchPostOffice:
        maxAttempts: '3'
        waitDuration: 1s
        retryExceptions:
          - java.lang.Exception
        ignoreExceptions:
          - com.vks.cbp.exception.InvalidPinCodeException
  circuitbreaker:
    instances:
      searchPinCode:
        waitDurationInOpenState: 10s
        failureRateThreshold: '100'
        permittedNumberOfCallsInHalfOpenState: '2'
        automaticTransitionFromOpenToHalfOpenEnabled: 'true'
        minimumNumberOfCalls: '2'
        slidingWindowType: 'COUNT_BASED'
        slidingWindowSize: '2'
        registerHealthIndicator: 'true'
        #slowCallDurationThreshold: 3s #Calls taking longer than this duration are considered "slow" and count toward the slowCallRateThreshold.
        #slowCallRateThreshold: '80' #The percentage of slow calls that, if exceeded, contributes to opening the circuit.
      searchPostOffice:
        waitDurationInOpenState: 10s
        failureRateThreshold: '50'
        permittedNumberOfCallsInHalfOpenState: '2'
        automaticTransitionFromOpenToHalfOpenEnabled: 'true'
        minimumNumberOfCalls: '2'
        slidingWindowType: 'COUNT_BASED'
        slidingWindowSize: '2'
        registerHealthIndicator: 'true'
        #slowCallDurationThreshold: 3s #Calls taking longer than this duration are considered "slow" and count toward the slowCallRateThreshold.
        #slowCallRateThreshold: '80' #The percentage of slow calls that, if exceeded, contributes to opening the circuit.
    configs:
      default:
        waitDurationInOpenState: 7s #The duration the circuit breaker stays in the OPEN state before automatically transitioning to HALF_OPEN.
        failureRateThreshold: '50' #The percentage of failed calls (or slow calls if slow-call-rate-threshold is also met) that will cause the circuit breaker to transition from CLOSED to OPEN.
        permittedNumberOfCallsInHalfOpenState: '3' #The number of test calls allowed in the HALF_OPEN state to determine if the service has recovered.
        automaticTransitionFromOpenToHalfOpenEnabled: 'true' #Determines if the transition from OPEN to HALF_OPEN should happen automatically after the wait duration.
        minimumNumberOfCalls: '5' #The minimum number of calls that must be recorded within the sliding window before the failure rate is calculated and the circuit can be opened.
        eventConsumerBufferSize: '10'
        slidingWindowType: 'COUNT_BASED' #Specifies whether the sliding window is COUNT_BASED or TIME_BASED.
        slidingWindowSize: '10' #The number of calls (count-based) or the time period (time-based) over which metrics are collected to calculate the failure rate.
        registerHealthIndicator: 'true' #If true, a health indicator for the circuit breaker instance will be exposed via the Spring Boot Actuator endpoint (e.g., /actuator/health).